from yacs.config import CfgNode as CN


_C = CN()

_C.INPUT = CN()
_C.INPUT.LATENCY_OVERESTIMATE_RATIO = 1.0
_C.INPUT.COMM_COST_SCALING_FACTOR = 1.0

_C.BEAM_SEARCH = CN()
_C.BEAM_SEARCH.BEST_K = 10
_C.BEAM_SEARCH.ACC_PROFILE_SAMPLE_LIMIT = None
_C.BEAM_SEARCH.PER_ASSIGNMENT_NODE_EXPANSION_LIMIT = None

_C.WORKER_ASSIGNMENT = CN()
_C.WORKER_ASSIGNMENT.STRATEGY = 'same-tier'
_C.WORKER_ASSIGNMENT.TIER_ALLOCATION_STRATEGY = 'dp'
_C.WORKER_ASSIGNMENT.MAX_NUM_ASSIGN_ORDERS = None
_C.WORKER_ASSIGNMENT.BEST_K_ASSIGNMENTS = None

_C.WORKER_PARTITION = CN()
_C.WORKER_PARTITION.STRATEGY = "min-cut"
_C.WORKER_PARTITION.NUM_TIERS = 2
_C.WORKER_PARTITION.LOUVAIN_RESOLUTION = 0.5
_C.WORKER_PARTITION.LOUVAIN_THRESHOLD = 1e-07
_C.WORKER_PARTITION.GREEDY_MODULARITY_RESOLUTION = 0.5


def get_cfg_defaults():
    return _C.clone()