[package]
name = "kafkaesque"
version = "0.12.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]
edition = "2018"

[dependencies]
clap="*"
abomonation = { path = "../abomonation", version = "0.7.3" }
timely = { path = "../timely" }

[dependencies.rdkafka]
version = "0.23.0"
