logs:
    dir_logs: logs/variants/mutan_noatt_resnet18
vqa:
    dataset: VQA
    dir: data/vqa
    trainsplit: train
    nans: 2000
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/coco
    arch: resnet18 
    mode: noatt
    size: 448
vgenome:
    trainsplit: train
    dir: data/vgenome
    arch: resnet18
    mode: noatt
    size: 448
    nans: 2000
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
model:
    arch: MutanNoAtt
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    fusion:
        dim_v: 512
        dim_q: 2400
        dim_hv: 360
        dim_hq: 360
        dim_mm: 360
        R: 10
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: tanh
        activation_q: tanh
        dropout_hv: 0
        dropout_hq: 0
    classif:
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 512
    epochs: 100
