[workspace]
members = [
    "bytes",
    "communication",
    "kafkaesque",
    "logging",
    "timely",
    "pipeline_examples",
    "abomonation",
    "abomonation_derive"
]

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false
