INPUT:
  LATENCY_OVERESTIMATE_RATIO: 1.0
  COMM_COST_SCALING_FACTOR: 0.1

BEAM_SEARCH:
  BEST_K: 10
  ACC_PROFILE_SAMPLE_LIMIT: None
  PER_ASSIGNMENT_NODE_EXPANSION_LIMIT: None

WORKER_ASSIGNMENT:
  STRATEGY: "multiple-tiers"
  TIER_ALLOCATION_STRATEGY: 'greedy'
  MAX_NUM_ASSIGN_ORDERS: 10
  BEST_K_ASSIGNMENTS: 10